# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('urls', models.URLField()),
                ('title', models.TextField(default='000', unique=True)),
            ],
        ),
    ]
