# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-26 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('urls', models.URLField(default='000', unique=True)),
                ('facility', models.TextField()),
                ('title', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='urls',
            field=models.URLField(default='000', unique=True),
        ),
    ]
